-- Referral bindings (on-chain ReferrerSet mirror)
CREATE TABLE IF NOT EXISTS referral_bindings (
  invitee_address text PRIMARY KEY,
  referrer_address text NOT NULL,
  bound_tx_hash text,
  bound_at timestamptz DEFAULT now() NOT NULL,
  CHECK (invitee_address = lower(invitee_address)),
  CHECK (referrer_address = lower(referrer_address)),
  CHECK (invitee_address <> referrer_address)
);

CREATE INDEX IF NOT EXISTS idx_referral_bindings_referrer
  ON referral_bindings (referrer_address, bound_at DESC);

-- Referrer fee claim history (creator_fee_claims mirror)
CREATE TABLE IF NOT EXISTS referrer_fee_claims (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_address text NOT NULL,
  amount_bnb numeric(78,18) NOT NULL,
  tx_hash text NOT NULL,
  log_index integer DEFAULT 0 NOT NULL,
  block_number bigint NOT NULL,
  block_time timestamptz NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT referrer_fee_claims_amount_bnb_check CHECK (amount_bnb > 0),
  CONSTRAINT referrer_fee_claims_referrer_address_check CHECK (referrer_address = lower(referrer_address)),
  CONSTRAINT referrer_fee_claims_tx_hash_log_index_key UNIQUE (tx_hash, log_index)
);

CREATE INDEX IF NOT EXISTS idx_referrer_fee_claims_referrer
  ON referrer_fee_claims (referrer_address, block_time DESC);

-- Per-trade referrer fee attribution
ALTER TABLE trades
  ADD COLUMN IF NOT EXISTS referrer_fee_zug numeric(78,18) DEFAULT 0 NOT NULL;
