export const pumpAirdropManagerAbi = [
  {
    type: "function",
    name: "admin",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "treasury",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nextAirdropId",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "remainingBalance",
    inputs: [{ name: "airdropId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "sweepRemainder",
    inputs: [{ name: "airdropId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createAirdrop",
    inputs: [
      { name: "linkedToken", type: "address" },
      { name: "rewardToken", type: "address" },
      { name: "rewardAmount", type: "uint256" },
      { name: "rulesHash", type: "bytes32" },
      { name: "qualifyStart", type: "uint64" },
      { name: "qualifyEnd", type: "uint64" },
    ],
    outputs: [{ name: "airdropId", type: "uint256" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "claim",
    inputs: [
      { name: "airdropId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "proof", type: "bytes32[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "airdrops",
    inputs: [{ name: "airdropId", type: "uint256" }],
    outputs: [
      { name: "creator", type: "address" },
      { name: "linkedToken", type: "address" },
      { name: "rewardToken", type: "address" },
      { name: "totalFunded", type: "uint256" },
      { name: "totalAllocated", type: "uint256" },
      { name: "totalClaimed", type: "uint256" },
      { name: "rulesHash", type: "bytes32" },
      { name: "merkleRoot", type: "bytes32" },
      { name: "qualifyStart", type: "uint64" },
      { name: "qualifyEnd", type: "uint64" },
      { name: "claimStart", type: "uint64" },
      { name: "claimEnd", type: "uint64" },
      { name: "status", type: "uint8" },
      { name: "remainderSwept", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "hasClaimed",
    inputs: [
      { name: "airdropId", type: "uint256" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AirdropCreated",
    inputs: [
      { name: "airdropId", type: "uint256", indexed: true },
      { name: "creator", type: "address", indexed: true },
      { name: "linkedToken", type: "address", indexed: true },
      { name: "rewardToken", type: "address", indexed: false },
      { name: "totalFunded", type: "uint256", indexed: false },
      { name: "rulesHash", type: "bytes32", indexed: false },
      { name: "qualifyStart", type: "uint64", indexed: false },
      { name: "qualifyEnd", type: "uint64", indexed: false },
      { name: "claimStart", type: "uint64", indexed: false },
      { name: "claimEnd", type: "uint64", indexed: false },
    ],
  },
] as const;
